#!/usr/bin/env bash

# USE:
#
#   * br URL              # open URL in the default browser
#   * br --listen         # starts a browser daemon -- handy when trying to
#                         # open URLs from a remote ssh session

BR_REMOTE_PORT=${BR_REMOTE_PORT:-5557}

listen() {
    echo "Listening on port ${BR_REMOTE_PORT}..."
    while (true); do
        python <<END
from __future__ import print_function
import socket, subprocess

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('localhost', ${BR_REMOTE_PORT}))
s.listen(1)
remote, _ = s.accept()
input = b''
while True:
    data = remote.recv(1024)
    if not data:
        break
    input += data
process = subprocess.Popen(['$0', input], stdin=subprocess.PIPE)
process.wait()
print('Open: ' + input)
remote.close()
s.close()
END
        if [ $? -ne 0 ]; then
            break
        fi
    done
}

myopen() {
    if env | grep --quiet -F SSH_TTY; then
        echo -n "$@" | nc -N localhost ${BR_REMOTE_PORT}
    elif hash open 2>/dev/null; then
        open "$@"
    elif hash cygstart 2>/dev/null; then
        cygstart "$@"
    else
        explorer.exe "$@"
    fi
}

if [ "$1" = "--listen" ]; then
    listen
else
    myopen "$@"
fi
